name: ğŸ“¦ Build k3s RPM

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ”„ Checkout code
      uses: actions/checkout@v2

    - name: ğŸ§° Setup RPMBuild environment
      run: |
        sudo apt-get install rpm
        mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
        echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros

    - name: â¬‡ï¸ Download k3s binary
      run: |
        curl -L -o ~/rpmbuild/SOURCES/k3s https://github.com/k3s-io/k3s/releases/latest/download/k3s

    - name: ğŸ­ Build RPM
      run: |
        cp src/scripts/* ~/rpmbuild/SOURCES/
        cp src/k3s.spec ~/rpmbuild/SPECS/k3s.spec
        rpmbuild -ba ~/rpmbuild/SPECS/k3s.spec

    - name: ğŸšš Upload RPM
      uses: actions/upload-artifact@v2
      with:
        name: k3s.rpm
        path: ~/rpmbuild/RPMS/**/*.rpm
